repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

  # Python formatting and linting with ruff
  # Using local hooks due to NixOS dynamic linking issues with pre-built binaries
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check --fix --exit-non-zero-on-fix
        language: system
        types: [python]
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types: [python]

  # Python import sorting
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --profile black
        language: system
        types: [python]

