version: '3.8'

services:
  bot:
    build: .
    depends_on:
      - postgres
    environment:
      - LOG_LEVEL=INFO
      - DATABASE_URL=postgresql://joinerbot:password@postgres:5432/joinerbot
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - JOINERBOT_WATCHED_CHANNEL="general (hop in!)"
      - JOINERBOT_TARGET_CHANNEL="general-notifications"
    restart: unless-stopped
    
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=joinerbot
      - POSTGRES_USER=joinerbot
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
